### ISSUE TITLE
Несовместимость с controlling

### ISSUE THREAD

**Issue by Rozbiynk** [DimasKama/VisualKeys#1]
Мод заменяет нижнюю панель, делая невозможным посмотреть меню кнопок из "Назначения клавиш"
![изображение](https://github.com/user-attachments/assets/6f19257d-fa08-4148-b078-88c6e398de05)
![изображение](https://github.com/user-attachments/assets/53713e49-0dca-4df0-87f2-6d2c6b9fd16b)

**Comment by DimasKama** [comment]
Added controlling mod compat in [VisualKeys 0.0.4](https://modrinth.com/mod/visualkeys/version/J6klQGmP)
![image](https://github.com/user-attachments/assets/fb5ba7ec-76fb-4f24-a0cc-f342483aa6e3)
